---
# tasks file for apigee-opdk-yum-repository-proxy-config
- name: Configure Apigee Yum repositories
  become: true
  yum_repository:
     enabled: "{{ item.enabled | default(true) }}"
     state: "{{ item.state | default('present') }}"
     name: "{{ item.repo_id }}"
     description: "{{ item.name }}"
     baseurl: "{{ item.baseurl }}"
     gpgcheck: "{{ item.gpgcheck | default(0)}}"
     gpgkey: "{{ item.gpgkey }}"
     priority: "{{ item.priority | default('') }}"
     exclude: "{{ item.exclude | default('') }}"
     file: '{{ item.repo_filename }}'
     sslverify: '{{ item.sslverify | default(false) }}'
  with_items: "{{ yum_repositories }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: yum_repositories is defined
