---
# tasks file for apigee-opdk-yum-repository-proxy-config
- name: Configure Apigee Yum repositories
  yum_repository:
     enabled: "{{ item.enabled | default(true) }}"
     state: "{{ item.state | default('present') }}"
     name: "{{ item.repo_id }}"
     repo_id: "{{ item.repo_id }}"
     description: "{{ item.name | default('') }}"
     baseurl: "{{ item.baseurl | default('') }}"
     gpgcheck: "{{ item.gpgcheck | default(0) }}"
     gpgkey: "{{ item.gpgkey | default('') }}"
     priority: "{{ item.priority | default(5) }}"
     exclude: "{{ item.exclude | default('') }}"
     file: '{{ item.repo_filename }}'
     sslverify: '{{ item.sslverify | default('') }}'
     proxy: "{{ item.proxy | default('') }}"
     proxy_password: "{{ item.proxy_password | default('') }}"
     proxy_username: "{{ item.proxy_username | default('') }}"
  with_items: "{{ yum_repositories }}"
  when: yum_repositories is defined
