---
# tasks file for apigee-opdk-yum-repository-proxy-config
- name: Configure Apigee Yum repositories
  yum_repository:
     enabled: "{{ item.enabled | default(true) }}"
     state: "{{ item.state | default('present') }}"
     name: "{{ item.repo_id }}"
     description: "{{ item.name }}"
     baseurl: "{{ item.baseurl }}"
     gpgcheck: "{{ item.gpgcheck }}"
     gpgkey: "{{ item.gpgkey }}"
     priority: "{{ item.priority }}"
     exclude: "{{ item.exclude }}"
     file: '{{ item.repo_filename }}'
     sslverify: '{{ item.sslverify }}'
  with_items: "{{ yum_repositories }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: yum_repositories is defined
