---
# tasks file for apigee-opdk-yum-repository-proxy-config
- include: with_proxy.yml
  when: apigee_yum_repositories is defined and https_proxy is defined and https_proxy | trim != '' and http_proxy is defined and http_proxy | trim != ''

- include: with_no_proxy.yml
  when: apigee_yum_repositories is defined and (https_proxy is not defined or https_proxy | trim == '') and (http_proxy is not defined or http_proxy | trim == '')
